### ISSUE TITLE
Update to jupyter-js-services 0.5

### ISSUE THREAD

**Issue by jhpedemonte** [jupyter-incubator/dashboards_server#40]
(We're currently at 0.3.x)

Major change is that `commOpened` signal is gone, replaced with `registerCommTarget()`.

---

**Tasks:**
- [x] Replace use of `commOpened` with `registerCommTarget()`.
- [x] Fix `display_data` bug with `jupyter-js-services` (jupyter/jupyter-js-services/pull/94)
- [x] Update `ipywidgets` to use latest `jupyter-js-services` (ipython/ipywidgets/issues/381)
- [x] Update `declarativewidgets` to latest `jupyter-js-services`.
- [x] Update `declarativewidgets` to latest `ipywidgets` (https://github.com/jupyter-incubator/declarativewidgets/pull/157#issuecomment-187417837).
- [x] Don't build `jquery-ui` into `ipywidgets`, since we also use it and this leads to code duplication and bloat.

**Comment by parente** [comment]
Not sure if the widgets are dependent on the old API or not. Or if the use of the commOpened signal is in the code here.

**Comment by jhpedemonte** [comment]
This will require update to ipywidgets as well. They're using `commOpened` in the shim.

**Comment by jhpedemonte** [comment]
Running **test_markdown.ipynb**, I get a validation error on one of the comm messages coming back (formatted for legibility):

```json
{
	"buffers": [],
	"metadata": {},
	"channel": "iopub",
	"header": {
		"date": "2016-02-18T22:49:12.298806",
		"username": "username",
		"version": "5.0",
		"msg_type": "display_data",
		"session": "5ccbf8f9-ec7a-4002-8f1a-701d0ddc8c2c",
		"msg_id": "4248e9ed-ab0b-4ed7-b0e1-0424206621bc"
	},
	"content": {
		"data": {
			"text/plain": "<IPython.core.display.HTML object>",
			"text/html": "<small>I am a code %%html cell with &lt;small&gt; wrapping my <strong>content</strong> which includes <a href=\"http://ibm.com\">a link in HTML</a></small>"
		},
		"metadata": {}
	},
	"msg_type": "display_data",
	"parent_header": {
		"date": "2016-02-18T22:49:12.285732",
		"username": "",
		"version": "5.0",
		"msg_type": "execute_request",
		"session": "d5ac50d5c40d47d30ef37ed3d73a9fa3",
		"msg_id": "78f3a1c80b804109f267acddb853668a"
	},
	"msg_id": "4248e9ed-ab0b-4ed7-b0e1-0424206621bc"
}
```

Seems that this [commit](https://github.com/jupyter/jupyter-js-services/commit/7cc7aabc214bd83b63ca7b57d3aa02217e180ce9) added additional validation and for a message of type `display_data`, it **expects** `msg.content` to have a `source` property and for it to be a string. As you can see, above message does not have that property.

Not sure if this is a bug with `jupyter-js-services` or with the backend not sending the correct message format.

@blink1073, should `validateIOPubKernelMessageContent()` check if `msg.content` has the property before checking its type? Or is `source` always required for this type of message?

**Comment by jhpedemonte** [comment]
[Docs](http://jupyter-client.readthedocs.org/en/latest/messaging.html?highlight=display_data#display-data) say `source` **was** previously used for `display_data` messages but was **removed** in "V5".

**Comment by blink1073** [comment]
I'll take out the check for it.

**Comment by blink1073** [comment]
See: https://github.com/jupyter/jupyter-js-services/pull/94.

**Comment by jhpedemonte** [comment]
Thanks, I was just about to test that. I'll add a comment on how it turns out.

**Comment by parente** [comment]
@jhpedemonte When we bump to newer ipywidgets, reminder that we need to remove the workaround here: https://github.com/jupyter-incubator/dashboards_server/blob/master/public/js/widget-manager.js#L112

I wonder, though, if we should submit a PR against ipywidgets to just delegate to one handler per channel instead of a handler per channel + message type. @jdfreder said we're basically the only consumer of this API at the moment. All we're going to do is register N functions now and delegate to `consumeMessage` which seems silly.

**Comment by jhpedemonte** [comment]
Opened https://github.com/ipython/ipywidgets/issues/381 to update their **services-shim.js** to new API.

**Comment by jhpedemonte** [comment]
Was able to get ipywidgets working. Uploaded patch to https://github.com/ipython/ipywidgets/pull/382.

**Comment by jhpedemonte** [comment]
`this.$dropbutton.dropdown is not a function` error is being caused by Bootstrap JS not getting properly invoked (it seems). Bootstrap is compiled into our *jupyter-js-widgets.js*, which is obviously loaded into the page.

I'm not familiar with bootstrap.js -- reading the docs it looks like it just needs to be loaded onto the page. Is it a timing issue? Does bootstrap JS need to be loaded before the page contents?

In the ipywidgets' examples, all the JS is built into a single file, but not in project.

**Comment by jhpedemonte** [comment]
@jdfreder, any idea about comment above?

**Comment by jhpedemonte** [comment]
Ah, I found it. The [jquery.js](https://github.com/ipython/ipywidgets/blob/master/jupyter-js-widgets/src/jquery.js) file in ipywidgets looks for jquery. If it is already there, that code does nothing. If it is *not* there, then it requires both jquery-ui and bootstrap.

My understanding is that this will (soon?) go away. So for now, I think the best solution on our end is to not compile Bootstrap into *jupyter-js-widgets.js* and require our own copy.

**Comment by jdfreder** [comment]
> Ah, I found it. The jquery.js file in ipywidgets looks for jquery. If it is already there, that code does nothing. If it is not there, then it requires both jquery-ui and bootstrap.
> 
> My understanding is that this will (soon?) go away. So for now, I think the best solution on our end is to not compile Bootstrap into jupyter-js-widgets.js and require our own copy.

Yeah, bootstrap should die at some point soon (AFAIK).  Bootstrap+jquery+jqueryui+typeahead+jquerytour globals, fun stuff!

**Comment by parente** [comment]
Fixed by #114  for the time being. We'll continue to track changes and bump versions.
